title: C++ Crash Course
description: Notes taken on reading C++ Crash Course by Josh Lospinosa, First edition.
theme: just-the-docs

url: https://efuquen.github.io/cpp_crash_course

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
